apiVersion: v1
kind: ServiceAccount
metadata:
  name: sdnc-svc-account

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: sdnc-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "nodes","nodes/proxy","services","namespaces"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sdnc-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: sdnc-svc-account # Name of the ServiceAccount
  namespace: default
roleRef:
  kind: ClusterRole # This must be Role or ClusterRole
  name: sdnc-role # This must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io


